import type { Metadata } from "next";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import { Inter } from "next/font/google";
import { AuthProvide } from "@/context/AuthContext";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Provider } from "react-redux";
import { store } from "@/state/store";
import Providers from "@/utils/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
